# Generated by Django 5.0.3 on 2024-12-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedarticle',
            name='url',
            field=models.TextField(default='google.com'),
            preserve_default=False,
        ),
    ]
