# Generated by Django 5.0.3 on 2024-12-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savedarticle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedarticle',
            name='published_at',
            field=models.TextField(default='2021-02-02T21:39:35-08:00'),
            preserve_default=False,
        ),
    ]
