# Generated by Django 5.0.3 on 2024-12-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_savedarticle_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='imgUrl',
            field=models.TextField(null=True),
        ),
    ]
